global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'node_exporter_metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['li2095-15.members.linode.com:9100']
  - job_name: 'process_exporter_metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['li2095-15.members.linode.com:9256']
